AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service & Task Definition

Parameters:
  ECSCluster:
    Type: String
  ServiceName:
    Type: String
  ContainerName:
    Type: String
  ECRImage:
    Type: String
  DesiredCount:
    Type: Number
    Default: 1

Resources:
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: arn:aws:iam::123456789012:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref ECRImage
          PortMappings:
            - ContainerPort: 80

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: [subnet-abc123, subnet-def456]
          SecurityGroups: [sg-0123456789abcdef0]