name: CI/CD Dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ECR_URI: ${{ secrets.ECR_REPOSITORY }}
      CLUSTER_NAME_DEV: ${{ secrets.CLUSTER_NAME_DEV }}
      SERVICE_NAME_DEV: ${{ secrets.SERVICE_NAME_DEV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-west-2

      - name: Build Docker image
        run: |
          docker build -t $ECR_URI:${{ github.sha }} .

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to ECR
        run: |
          docker tag $ECR_URI:${{ github.sha }} $ECR_URI:latest
          docker push $ECR_URI:${{ github.sha }}
          docker push $ECR_URI:latest

      - name: Update ECS service
        uses: aws-actions/amazon-ecs-update-service@v1
        with:
          cluster: $CLUSTER_NAME_DEV
          service: $SERVICE_NAME_DEV
          image: $ECR_URI:${{ github.sha }}